---
- name: Criar arquivo vazio no Windows
  hosts: all

  tasks:
    - name: Run an executable using win_command
      win_command: where powershell
      win_command: C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe 